export const phaseOrder = [
  { key: '事前準備', label: '事前準備（〜11月上旬）', color: '#cddafd' },
  { key: 'PoC', label: 'PoCフェーズ（11月中旬〜下旬）', color: '#ffe3e3' },
  { key: '現状分析', label: '現状分析（12月初旬）', color: '#fff3bf' },
  { key: '方向性策定', label: '方向性策定（12月中旬）', color: '#ece4f6' },
  { key: '中間報告', label: '中間報告（12月末）', color: '#fad2e1' },
  { key: '最終成果', label: '最終成果（1月初旬〜中旬）', color: '#d9f2ff' },
  { key: '随時', label: '随時実施', color: '#e2f0cb' },
];

export const tasks = [
  {
    id: 'todo-1',
    todoRef: 'Todo 1',
    title: 'NDAドラフト作成',
    phase: '事前準備',
    window: '〜11月上旬',
    priority: 'critical',
    status: '未着手',
    owner: '平野 雅也',
    deliverable: '1.1 NDA',
    notes: 'ドラフト作成、条項確認、送付・署名、原本管理',
  },
  {
    id: 'todo-2',
    todoRef: 'Todo 2',
    title: 'ヒアリング計画表',
    phase: '事前準備',
    window: '〜11月上旬',
    priority: 'critical',
    status: '未着手',
    owner: '平野 雅也',
    deliverable: '1.2 ヒアリング計画表',
    notes: '対象部署、日程、質問票、資料リストを整理',
  },
  {
    id: 'todo-3',
    todoRef: 'Todo 3',
    title: '質問票テンプレ＆情報収集チェックリスト',
    phase: '事前準備',
    window: '〜11月上旬',
    priority: 'critical',
    status: '未着手',
    owner: 'ナレッジ担当',
    deliverable: '6.1 / 6.2 テンプレート',
    notes: '業務・システム・課題・データ管理の質問を整備',
  },
  {
    id: 'todo-4',
    todoRef: 'Todo 4',
    title: 'キックオフ資料作成',
    phase: '事前準備',
    window: '〜11月上旬',
    priority: 'critical',
    status: '未着手',
    owner: '平野 雅也',
    deliverable: 'キックオフ資料',
    notes: '概要・スケジュール・役割・資料依頼を明確化',
  },
  {
    id: 'todo-5',
    todoRef: 'Todo 5',
    title: 'キックオフミーティング実施',
    phase: 'PoC',
    window: '11月中旬',
    priority: 'critical',
    status: '未着手',
    owner: '平野 雅也',
    deliverable: '議事録（Word/Notion）',
    notes: 'Zoom開催、期待値すり合わせ、Q&A',
  },
  {
    id: 'todo-7',
    todoRef: 'Todo 7',
    title: '部署ヒアリング（2〜3回）',
    phase: 'PoC',
    window: '11月下旬',
    priority: 'critical',
    status: '未着手',
    owner: 'ヒアリングチーム',
    deliverable: '各部署議事録',
    notes: '業務フロー・システム・課題・データの実態把握',
  },
  {
    id: 'todo-9',
    todoRef: 'Todo 9',
    title: '現行業務フロー図',
    phase: '現状分析',
    window: '12月初旬',
    priority: 'critical',
    status: '未着手',
    owner: '業務設計チーム',
    deliverable: '2.1 現行業務フロー図',
    notes: '部署別業務・データ・連携の可視化',
  },
  {
    id: 'todo-10',
    todoRef: 'Todo 10',
    title: '課題リスト',
    phase: '現状分析',
    window: '12月初旬',
    priority: 'critical',
    status: '未着手',
    owner: '課題整理担当',
    deliverable: '2.2 課題リスト',
    notes: '非効率・属人化・システム課題を優先度付きで整理',
  },
  {
    id: 'todo-13',
    todoRef: 'Todo 13',
    title: 'To-Beマップ',
    phase: '方向性策定',
    window: '12月中旬',
    priority: 'critical',
    status: '未着手',
    owner: 'ビジョン策定チーム',
    deliverable: '4.1 To-Beマップ',
    notes: '2030年像、理想フロー、データ活用方針',
  },
  {
    id: 'todo-16',
    todoRef: 'Todo 16',
    title: 'DX推進中間レポート',
    phase: '中間報告',
    window: '12月末',
    priority: 'critical',
    status: '未着手',
    owner: 'レポートチーム',
    deliverable: '3.1 DX推進中間レポート',
    notes: '現状マップ、課題整理、方向性案',
  },
  {
    id: 'todo-18',
    todoRef: 'Todo 18',
    title: 'DXロードマップ（5ヵ年）',
    phase: '最終成果',
    window: '1月初旬',
    priority: 'critical',
    status: '未着手',
    owner: 'ロードマップ担当',
    deliverable: '5.1 DXロードマップ',
    notes: '年次工程・KPI・概算費用・体制',
  },
  {
    id: 'todo-22',
    todoRef: 'Todo 22',
    title: '最終報告スライド',
    phase: '最終成果',
    window: '1月中旬',
    priority: 'critical',
    status: '未着手',
    owner: 'プレゼン担当',
    deliverable: '5.5 提案資料スライド',
    notes: 'エグゼクティブサマリー〜次ステップ',
  },
  {
    id: 'todo-25',
    todoRef: 'Todo 25',
    title: '週次進捗レポート',
    phase: '随時',
    window: '毎週',
    priority: 'high',
    status: '未着手',
    owner: 'PMO',
    deliverable: '7.2 進捗報告テンプレ',
    notes: '進捗・次週予定・課題/リスクの共有',
  },
];

export const deliverables = [
  {
    id: '1.1',
    title: 'NDA（機密保持契約書）',
    window: 'プロジェクト開始前',
    format: 'PDF',
    owner: '法務',
    status: '準備中',
  },
  {
    id: '2.1',
    title: '現行業務フロー図',
    window: '11月下旬',
    format: 'PowerPoint / Miro',
    owner: '業務設計チーム',
    status: '未着手',
  },
  {
    id: '3.1',
    title: 'DX推進中間レポート',
    window: '12月末',
    format: 'PowerPoint / Word',
    owner: 'レポートチーム',
    status: '未着手',
  },
  {
    id: '4.1',
    title: 'To-Beマップ',
    window: '12月末',
    format: 'PowerPoint / Miro',
    owner: 'ビジョン策定チーム',
    status: '未着手',
  },
  {
    id: '5.1',
    title: 'DXロードマップ（5ヵ年計画）',
    window: '1月末',
    format: 'PowerPoint + Excel',
    owner: 'ロードマップ担当',
    status: '未着手',
  },
  {
    id: '5.5',
    title: '最終報告スライド',
    window: '1月中旬',
    format: 'PowerPoint',
    owner: 'プレゼン担当',
    status: '未着手',
  },
];

export const meetings = [
  {
    title: 'キックオフミーティング',
    window: '11月中旬',
    channel: 'オンライン（Zoom）',
    focus: '進め方・役割、期待値すり合わせ',
  },
  {
    title: '現状ヒアリング（2〜3回）',
    window: '11月下旬',
    channel: 'オンライン or 現地',
    focus: '各部署ヒアリングと追加資料依頼',
  },
  {
    title: '中間報告ミーティング',
    window: '12月中旬',
    channel: 'オンライン',
    focus: '中間レポート提示と方向性レビュー',
  },
  {
    title: '最終報告ミーティング',
    window: '1月中旬',
    channel: '対面またはオンライン',
    focus: 'ロードマップ承認と次フェーズ提案',
  },
];

export const risks = [
  {
    name: 'ヒアリング日程調整の遅延',
    impact: '高',
    mitigation: '早期調整と複数候補日提示',
  },
  {
    name: '必要資料の受領遅延',
    impact: '中',
    mitigation: '事前リスト共有と定期リマインド',
  },
  {
    name: '方向性の大幅修正',
    impact: '高',
    mitigation: 'ミニレビューで早期フィードバック取得',
  },
  {
    name: '成果物工数の超過',
    impact: '中',
    mitigation: 'バッファ確保と優先度明確化',
  },
];
